# Generated by Django 4.0.1 on 2022-02-02 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='descripton',
            new_name='description',
        ),
    ]
